version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build complete"
  post_build:
    commands:
      - zip -r fastapi-app.zip .

artifacts:
  files:
    - fastapi-app.zip
    - appspec.yml
    - scripts/*
